
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  annotations:
    aws.amazon.com/aws-codebuild-project-tags: app=backstage
    aws.amazon.com/aws-codepipeline-tags: app=backstage
spec:
  type: service
  owner: guests
  lifecycle: production
